<?php

namespace ContainerHKPq9Vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Importmap_RendererService extends App_KernelProdContainer
{
    /*
     * Gets the private 'asset_mapper.importmap.renderer' shared service.
     *
     * @return \Symfony\Component\AssetMapper\ImportMap\ImportMapRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['asset_mapper.importmap.renderer'] = new \Symfony\Component\AssetMapper\ImportMap\ImportMapRenderer(($container->privates['asset_mapper.importmap.manager'] ?? $container->load('getAssetMapper_Importmap_ManagerService')), 'UTF-8', 'https://ga.jspm.io/npm:es-module-shims@1.7.2/dist/es-module-shims.js', ['data-turbo-track' => 'reload']);
    }
}
