<?php

namespace ContainerHKPq9Vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodePostalRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CodePostalRepository' shared autowired service.
     *
     * @return \App\Repository\CodePostalRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CodePostalRepository'] = new \App\Repository\CodePostalRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
