<?php

namespace ContainerHKPq9Vr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormBuilderInterfaceService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.7Wj9IIq.Symfony\Component\Form\FormBuilderInterface' shared service.
     *
     * @return \Symfony\Component\Form\FormBuilderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7Wj9IIq": it references interface "Symfony\\Component\\Form\\FormBuilderInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
