<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHKPq9Vr\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHKPq9Vr/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHKPq9Vr.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHKPq9Vr\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHKPq9Vr\App_KernelProdContainer([
    'container.build_hash' => 'HKPq9Vr',
    'container.build_id' => '11157f25',
    'container.build_time' => 1712154210,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHKPq9Vr');
