<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_account' => [[], ['_controller' => 'App\\Controller\\AccountController::index'], [], [['text', '/account']], [], [], []],
    'app_address_index' => [[], ['_controller' => 'App\\Controller\\AddressController::index'], [], [['text', '/account/address/']], [], [], []],
    'app_address_new' => [[], ['_controller' => 'App\\Controller\\AddressController::new'], [], [['text', '/account/address/new']], [], [], []],
    'app_address_show' => [['id'], ['_controller' => 'App\\Controller\\AddressController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/account/address']], [], [], []],
    'app_address_edit' => [['id'], ['_controller' => 'App\\Controller\\AddressController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/account/address']], [], [], []],
    'app_address_delete' => [['id'], ['_controller' => 'App\\Controller\\AddressController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/account/address']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'app_post_address' => [[], ['_controller' => 'App\\Controller\\Api\\ApiAddressController::index'], [], [['text', '/api/address']], [], [], []],
    'app_api_put_address' => [['id'], ['_controller' => 'App\\Controller\\Api\\ApiAddressController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/address']], [], [], []],
    'app_api_delete_address' => [['id'], ['_controller' => 'App\\Controller\\Api\\ApiAddressController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/address']], [], [], []],
    'app_api_api_order' => [[], ['_controller' => 'App\\Controller\\Api\\ApiOrderController::update'], [], [['text', '/api/order']], [], [], []],
    'app_stripe_payment-intent' => [['orderId'], ['_controller' => 'App\\Controller\\Api\\ApiStripeController::index'], [], [['variable', '/', '[^/]++', 'orderId', true], ['text', '/api/stripe/payment-intent']], [], [], []],
    'app_cart' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/cart']], [], [], []],
    'app_add_to_cart' => [['productId', 'count'], ['count' => 1, '_controller' => 'App\\Controller\\CartController::addToCart'], [], [['variable', '/', '[^/]++', 'count', true], ['variable', '/', '[^/]++', 'productId', true], ['text', '/cart/add']], [], [], []],
    'app_remove_to_cart' => [['productId', 'count'], ['count' => 1, '_controller' => 'App\\Controller\\CartController::removeToCart'], [], [['variable', '/', '[^/]++', 'count', true], ['variable', '/', '[^/]++', 'productId', true], ['text', '/cart/remove']], [], [], []],
    'app_checkout' => [[], ['_controller' => 'App\\Controller\\CheckoutController::index'], [], [['text', '/checkout']], [], [], []],
    'app_stripe_payment_success' => [[], ['_controller' => 'App\\Controller\\CheckoutController::paymentSuccess'], [], [['text', '/stripe/payment/success']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_product_by_slug' => [['slug'], ['_controller' => 'App\\Controller\\HomeController::showProduct'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/product']], [], [], []],
    'app_error' => [[], ['_controller' => 'App\\Controller\\HomeController::errorPage'], [], [['text', '/error']], [], [], []],
    'app_page' => [['slug'], ['_controller' => 'App\\Controller\\PageController::index'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/page']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
