<?php

namespace ContainerWJFQOt6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TWKm7ZSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tWKm7ZS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tWKm7ZS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoRep' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'pageRep' => ['privates', 'App\\Repository\\PageRepository', 'getPageRepositoryService', true],
            'settingsRep' => ['privates', 'App\\Repository\\SettingsRepository', 'getSettingsRepositoryService', true],
        ], [
            'categoRep' => 'App\\Repository\\CategoryRepository',
            'pageRep' => 'App\\Repository\\PageRepository',
            'settingsRep' => 'App\\Repository\\SettingsRepository',
        ]);
    }
}
