<?php

namespace ContainerMyTsi7d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A1byfg1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A1byfg1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A1byfg1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pageRep' => ['privates', 'App\\Repository\\PageRepository', 'getPageRepositoryService', true],
        ], [
            'pageRep' => 'App\\Repository\\PageRepository',
        ]);
    }
}
