<?php

namespace ContainerMyTsi7d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\StripeService' shared autowired service.
     *
     * @return \App\Services\StripeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'StripeService.php';

        return $container->privates['App\\Services\\StripeService'] = new \App\Services\StripeService(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\PaymentMethodRepository'] ?? $container->load('getPaymentMethodRepositoryService')));
    }
}
