<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaymentMethod extends \App\Entity\PaymentMethod implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null],
        "\0".parent::class."\0".'more_description' => [parent::class, 'more_description', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'prod_private_api_key' => [parent::class, 'prod_private_api_key', null],
        "\0".parent::class."\0".'prod_public_api_key' => [parent::class, 'prod_public_api_key', null],
        "\0".parent::class."\0".'test_private_api_key' => [parent::class, 'test_private_api_key', null],
        "\0".parent::class."\0".'test_public_api_key' => [parent::class, 'test_public_api_key', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'imageUrl' => [parent::class, 'imageUrl', null],
        'more_description' => [parent::class, 'more_description', null],
        'name' => [parent::class, 'name', null],
        'prod_private_api_key' => [parent::class, 'prod_private_api_key', null],
        'prod_public_api_key' => [parent::class, 'prod_public_api_key', null],
        'test_private_api_key' => [parent::class, 'test_private_api_key', null],
        'test_public_api_key' => [parent::class, 'test_public_api_key', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
