<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'billing_address' => [parent::class, 'billing_address', null],
        "\0".parent::class."\0".'carrier_id' => [parent::class, 'carrier_id', null],
        "\0".parent::class."\0".'carrier_name' => [parent::class, 'carrier_name', null],
        "\0".parent::class."\0".'carrier_price' => [parent::class, 'carrier_price', null],
        "\0".parent::class."\0".'client_name' => [parent::class, 'client_name', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isPayed' => [parent::class, 'isPayed', null],
        "\0".parent::class."\0".'orderDetails' => [parent::class, 'orderDetails', null],
        "\0".parent::class."\0".'order_cost' => [parent::class, 'order_cost', null],
        "\0".parent::class."\0".'order_cost_ttc' => [parent::class, 'order_cost_ttc', null],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null],
        "\0".parent::class."\0".'shipping_address' => [parent::class, 'shipping_address', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'stripeClientSecret' => [parent::class, 'stripeClientSecret', null],
        "\0".parent::class."\0".'taxe' => [parent::class, 'taxe', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        'billing_address' => [parent::class, 'billing_address', null],
        'carrier_id' => [parent::class, 'carrier_id', null],
        'carrier_name' => [parent::class, 'carrier_name', null],
        'carrier_price' => [parent::class, 'carrier_price', null],
        'client_name' => [parent::class, 'client_name', null],
        'created_at' => [parent::class, 'created_at', null],
        'id' => [parent::class, 'id', null],
        'isPayed' => [parent::class, 'isPayed', null],
        'orderDetails' => [parent::class, 'orderDetails', null],
        'order_cost' => [parent::class, 'order_cost', null],
        'order_cost_ttc' => [parent::class, 'order_cost_ttc', null],
        'quantity' => [parent::class, 'quantity', null],
        'shipping_address' => [parent::class, 'shipping_address', null],
        'status' => [parent::class, 'status', null],
        'stripeClientSecret' => [parent::class, 'stripeClientSecret', null],
        'taxe' => [parent::class, 'taxe', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
