<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'additional_infos' => [parent::class, 'additional_infos', null],
        "\0".parent::class."\0".'brand' => [parent::class, 'brand', null],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageUrls' => [parent::class, 'imageUrls', null],
        "\0".parent::class."\0".'isAvailable' => [parent::class, 'isAvailable', null],
        "\0".parent::class."\0".'isBestSeller' => [parent::class, 'isBestSeller', null],
        "\0".parent::class."\0".'isNewArrival' => [parent::class, 'isNewArrival', null],
        "\0".parent::class."\0".'more_description' => [parent::class, 'more_description', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'regular_price' => [parent::class, 'regular_price', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'solde_price' => [parent::class, 'solde_price', null],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        'additional_infos' => [parent::class, 'additional_infos', null],
        'brand' => [parent::class, 'brand', null],
        'categories' => [parent::class, 'categories', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'imageUrls' => [parent::class, 'imageUrls', null],
        'isAvailable' => [parent::class, 'isAvailable', null],
        'isBestSeller' => [parent::class, 'isBestSeller', null],
        'isNewArrival' => [parent::class, 'isNewArrival', null],
        'more_description' => [parent::class, 'more_description', null],
        'name' => [parent::class, 'name', null],
        'regular_price' => [parent::class, 'regular_price', null],
        'slug' => [parent::class, 'slug', null],
        'solde_price' => [parent::class, 'solde_price', null],
        'stock' => [parent::class, 'stock', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
