<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderDetails extends \App\Entity\OrderDetails implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'myOrder' => [parent::class, 'myOrder', null],
        "\0".parent::class."\0".'product_description' => [parent::class, 'product_description', null],
        "\0".parent::class."\0".'product_name' => [parent::class, 'product_name', null],
        "\0".parent::class."\0".'product_regular_price' => [parent::class, 'product_regular_price', null],
        "\0".parent::class."\0".'product_solde_price' => [parent::class, 'product_solde_price', null],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null],
        "\0".parent::class."\0".'subtotal' => [parent::class, 'subtotal', null],
        "\0".parent::class."\0".'taxe' => [parent::class, 'taxe', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        'created_at' => [parent::class, 'created_at', null],
        'id' => [parent::class, 'id', null],
        'myOrder' => [parent::class, 'myOrder', null],
        'product_description' => [parent::class, 'product_description', null],
        'product_name' => [parent::class, 'product_name', null],
        'product_regular_price' => [parent::class, 'product_regular_price', null],
        'product_solde_price' => [parent::class, 'product_solde_price', null],
        'quantity' => [parent::class, 'quantity', null],
        'subtotal' => [parent::class, 'subtotal', null],
        'taxe' => [parent::class, 'taxe', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
